#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmt.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLKS1")]
	public partial class QLKSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiTietDatPhong(ChiTietDatPhong instance);
    partial void UpdateChiTietDatPhong(ChiTietDatPhong instance);
    partial void DeleteChiTietDatPhong(ChiTietDatPhong instance);
    partial void InsertTienNghi(TienNghi instance);
    partial void UpdateTienNghi(TienNghi instance);
    partial void DeleteTienNghi(TienNghi instance);
    partial void InsertDiemDanhGia(DiemDanhGia instance);
    partial void UpdateDiemDanhGia(DiemDanhGia instance);
    partial void DeleteDiemDanhGia(DiemDanhGia instance);
    partial void InsertDonDatPhong(DonDatPhong instance);
    partial void UpdateDonDatPhong(DonDatPhong instance);
    partial void DeleteDonDatPhong(DonDatPhong instance);
    partial void InsertHinhAnh(HinhAnh instance);
    partial void UpdateHinhAnh(HinhAnh instance);
    partial void DeleteHinhAnh(HinhAnh instance);
    partial void InsertKhacHang(KhacHang instance);
    partial void UpdateKhacHang(KhacHang instance);
    partial void DeleteKhacHang(KhacHang instance);
    partial void InsertKhachSan(KhachSan instance);
    partial void UpdateKhachSan(KhachSan instance);
    partial void DeleteKhachSan(KhachSan instance);
    partial void InsertKhuVuc(KhuVuc instance);
    partial void UpdateKhuVuc(KhuVuc instance);
    partial void DeleteKhuVuc(KhuVuc instance);
    partial void InsertLoaiPhong(LoaiPhong instance);
    partial void UpdateLoaiPhong(LoaiPhong instance);
    partial void DeleteLoaiPhong(LoaiPhong instance);
    partial void InsertPhong(Phong instance);
    partial void UpdatePhong(Phong instance);
    partial void DeletePhong(Phong instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    #endregion
		
		public QLKSDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLKS1ConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLKSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiTietDatPhong> ChiTietDatPhongs
		{
			get
			{
				return this.GetTable<ChiTietDatPhong>();
			}
		}
		
		public System.Data.Linq.Table<TienNghi> TienNghis
		{
			get
			{
				return this.GetTable<TienNghi>();
			}
		}
		
		public System.Data.Linq.Table<DiemDanhGia> DiemDanhGias
		{
			get
			{
				return this.GetTable<DiemDanhGia>();
			}
		}
		
		public System.Data.Linq.Table<DonDatPhong> DonDatPhongs
		{
			get
			{
				return this.GetTable<DonDatPhong>();
			}
		}
		
		public System.Data.Linq.Table<HinhAnh> HinhAnhs
		{
			get
			{
				return this.GetTable<HinhAnh>();
			}
		}
		
		public System.Data.Linq.Table<KhacHang> KhacHangs
		{
			get
			{
				return this.GetTable<KhacHang>();
			}
		}
		
		public System.Data.Linq.Table<KhachSan> KhachSans
		{
			get
			{
				return this.GetTable<KhachSan>();
			}
		}
		
		public System.Data.Linq.Table<KhuVuc> KhuVucs
		{
			get
			{
				return this.GetTable<KhuVuc>();
			}
		}
		
		public System.Data.Linq.Table<LoaiPhong> LoaiPhongs
		{
			get
			{
				return this.GetTable<LoaiPhong>();
			}
		}
		
		public System.Data.Linq.Table<Phong> Phongs
		{
			get
			{
				return this.GetTable<Phong>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MaKH_AuTo1")]
		public int MaKH_AuTo1()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MaKH_AuTo2")]
		public int MaKH_AuTo2([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] ref string output)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), output);
			output = ((string)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.P_GetIDDonDatPhong")]
		public int P_GetIDDonDatPhong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			id = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.f_GetMaKH", IsComposable=true)]
		public string f_GetMaKH()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietDatPhong")]
	public partial class ChiTietDatPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dondat_id;
		
		private short _maks;
		
		private byte _maloai;
		
		private System.Nullable<int> _soluong;
		
		private System.Nullable<System.DateTime> _ngay_den;
		
		private System.Nullable<System.DateTime> _ngay_tra;
		
		private EntityRef<DonDatPhong> _DonDatPhong;
		
		private EntityRef<KhachSan> _KhachSan;
		
		private EntityRef<LoaiPhong> _LoaiPhong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondondat_idChanging(int value);
    partial void Ondondat_idChanged();
    partial void OnmaksChanging(short value);
    partial void OnmaksChanged();
    partial void OnmaloaiChanging(byte value);
    partial void OnmaloaiChanged();
    partial void OnsoluongChanging(System.Nullable<int> value);
    partial void OnsoluongChanged();
    partial void Onngay_denChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_denChanged();
    partial void Onngay_traChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_traChanged();
    #endregion
		
		public ChiTietDatPhong()
		{
			this._DonDatPhong = default(EntityRef<DonDatPhong>);
			this._KhachSan = default(EntityRef<KhachSan>);
			this._LoaiPhong = default(EntityRef<LoaiPhong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dondat_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int dondat_id
		{
			get
			{
				return this._dondat_id;
			}
			set
			{
				if ((this._dondat_id != value))
				{
					if (this._DonDatPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondondat_idChanging(value);
					this.SendPropertyChanging();
					this._dondat_id = value;
					this.SendPropertyChanged("dondat_id");
					this.Ondondat_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maks", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short maks
		{
			get
			{
				return this._maks;
			}
			set
			{
				if ((this._maks != value))
				{
					if (this._KhachSan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaksChanging(value);
					this.SendPropertyChanging();
					this._maks = value;
					this.SendPropertyChanged("maks");
					this.OnmaksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloai", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte maloai
		{
			get
			{
				return this._maloai;
			}
			set
			{
				if ((this._maloai != value))
				{
					if (this._LoaiPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaloaiChanging(value);
					this.SendPropertyChanging();
					this._maloai = value;
					this.SendPropertyChanged("maloai");
					this.OnmaloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_den", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_den
		{
			get
			{
				return this._ngay_den;
			}
			set
			{
				if ((this._ngay_den != value))
				{
					this.Onngay_denChanging(value);
					this.SendPropertyChanging();
					this._ngay_den = value;
					this.SendPropertyChanged("ngay_den");
					this.Onngay_denChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tra", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_tra
		{
			get
			{
				return this._ngay_tra;
			}
			set
			{
				if ((this._ngay_tra != value))
				{
					this.Onngay_traChanging(value);
					this.SendPropertyChanging();
					this._ngay_tra = value;
					this.SendPropertyChanged("ngay_tra");
					this.Onngay_traChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonDatPhong_ChiTietDatPhong", Storage="_DonDatPhong", ThisKey="dondat_id", OtherKey="id_ddp", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public DonDatPhong DonDatPhong
		{
			get
			{
				return this._DonDatPhong.Entity;
			}
			set
			{
				DonDatPhong previousValue = this._DonDatPhong.Entity;
				if (((previousValue != value) 
							|| (this._DonDatPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DonDatPhong.Entity = null;
						previousValue.ChiTietDatPhongs.Remove(this);
					}
					this._DonDatPhong.Entity = value;
					if ((value != null))
					{
						value.ChiTietDatPhongs.Add(this);
						this._dondat_id = value.id_ddp;
					}
					else
					{
						this._dondat_id = default(int);
					}
					this.SendPropertyChanged("DonDatPhong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachSan_ChiTietDatPhong", Storage="_KhachSan", ThisKey="maks", OtherKey="MaKS", IsForeignKey=true)]
		public KhachSan KhachSan
		{
			get
			{
				return this._KhachSan.Entity;
			}
			set
			{
				KhachSan previousValue = this._KhachSan.Entity;
				if (((previousValue != value) 
							|| (this._KhachSan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachSan.Entity = null;
						previousValue.ChiTietDatPhongs.Remove(this);
					}
					this._KhachSan.Entity = value;
					if ((value != null))
					{
						value.ChiTietDatPhongs.Add(this);
						this._maks = value.MaKS;
					}
					else
					{
						this._maks = default(short);
					}
					this.SendPropertyChanged("KhachSan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiPhong_ChiTietDatPhong", Storage="_LoaiPhong", ThisKey="maloai", OtherKey="MaLoai", IsForeignKey=true)]
		public LoaiPhong LoaiPhong
		{
			get
			{
				return this._LoaiPhong.Entity;
			}
			set
			{
				LoaiPhong previousValue = this._LoaiPhong.Entity;
				if (((previousValue != value) 
							|| (this._LoaiPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiPhong.Entity = null;
						previousValue.ChiTietDatPhongs.Remove(this);
					}
					this._LoaiPhong.Entity = value;
					if ((value != null))
					{
						value.ChiTietDatPhongs.Add(this);
						this._maloai = value.MaLoai;
					}
					else
					{
						this._maloai = default(byte);
					}
					this.SendPropertyChanged("LoaiPhong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TienNghi")]
	public partial class TienNghi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _MaKS;
		
		private System.Nullable<bool> _LeTan24h;
		
		private System.Nullable<bool> _ChoThueXe;
		
		private System.Nullable<bool> _CachAm;
		
		private System.Nullable<bool> _MayGiat;
		
		private System.Nullable<bool> _BonTam;
		
		private System.Nullable<bool> _Tivi;
		
		private System.Nullable<bool> _TuLanh;
		
		private EntityRef<KhachSan> _KhachSan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKSChanging(short value);
    partial void OnMaKSChanged();
    partial void OnLeTan24hChanging(System.Nullable<bool> value);
    partial void OnLeTan24hChanged();
    partial void OnChoThueXeChanging(System.Nullable<bool> value);
    partial void OnChoThueXeChanged();
    partial void OnCachAmChanging(System.Nullable<bool> value);
    partial void OnCachAmChanged();
    partial void OnMayGiatChanging(System.Nullable<bool> value);
    partial void OnMayGiatChanged();
    partial void OnBonTamChanging(System.Nullable<bool> value);
    partial void OnBonTamChanged();
    partial void OnTiviChanging(System.Nullable<bool> value);
    partial void OnTiviChanged();
    partial void OnTuLanhChanging(System.Nullable<bool> value);
    partial void OnTuLanhChanged();
    #endregion
		
		public TienNghi()
		{
			this._KhachSan = default(EntityRef<KhachSan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKS", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short MaKS
		{
			get
			{
				return this._MaKS;
			}
			set
			{
				if ((this._MaKS != value))
				{
					if (this._KhachSan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKSChanging(value);
					this.SendPropertyChanging();
					this._MaKS = value;
					this.SendPropertyChanged("MaKS");
					this.OnMaKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeTan24h", DbType="Bit")]
		public System.Nullable<bool> LeTan24h
		{
			get
			{
				return this._LeTan24h;
			}
			set
			{
				if ((this._LeTan24h != value))
				{
					this.OnLeTan24hChanging(value);
					this.SendPropertyChanging();
					this._LeTan24h = value;
					this.SendPropertyChanged("LeTan24h");
					this.OnLeTan24hChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChoThueXe", DbType="Bit")]
		public System.Nullable<bool> ChoThueXe
		{
			get
			{
				return this._ChoThueXe;
			}
			set
			{
				if ((this._ChoThueXe != value))
				{
					this.OnChoThueXeChanging(value);
					this.SendPropertyChanging();
					this._ChoThueXe = value;
					this.SendPropertyChanged("ChoThueXe");
					this.OnChoThueXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CachAm", DbType="Bit")]
		public System.Nullable<bool> CachAm
		{
			get
			{
				return this._CachAm;
			}
			set
			{
				if ((this._CachAm != value))
				{
					this.OnCachAmChanging(value);
					this.SendPropertyChanging();
					this._CachAm = value;
					this.SendPropertyChanged("CachAm");
					this.OnCachAmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MayGiat", DbType="Bit")]
		public System.Nullable<bool> MayGiat
		{
			get
			{
				return this._MayGiat;
			}
			set
			{
				if ((this._MayGiat != value))
				{
					this.OnMayGiatChanging(value);
					this.SendPropertyChanging();
					this._MayGiat = value;
					this.SendPropertyChanged("MayGiat");
					this.OnMayGiatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BonTam", DbType="Bit")]
		public System.Nullable<bool> BonTam
		{
			get
			{
				return this._BonTam;
			}
			set
			{
				if ((this._BonTam != value))
				{
					this.OnBonTamChanging(value);
					this.SendPropertyChanging();
					this._BonTam = value;
					this.SendPropertyChanged("BonTam");
					this.OnBonTamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tivi", DbType="Bit")]
		public System.Nullable<bool> Tivi
		{
			get
			{
				return this._Tivi;
			}
			set
			{
				if ((this._Tivi != value))
				{
					this.OnTiviChanging(value);
					this.SendPropertyChanging();
					this._Tivi = value;
					this.SendPropertyChanged("Tivi");
					this.OnTiviChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuLanh", DbType="Bit")]
		public System.Nullable<bool> TuLanh
		{
			get
			{
				return this._TuLanh;
			}
			set
			{
				if ((this._TuLanh != value))
				{
					this.OnTuLanhChanging(value);
					this.SendPropertyChanging();
					this._TuLanh = value;
					this.SendPropertyChanged("TuLanh");
					this.OnTuLanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachSan_TienNghi", Storage="_KhachSan", ThisKey="MaKS", OtherKey="MaKS", IsForeignKey=true)]
		public KhachSan KhachSan
		{
			get
			{
				return this._KhachSan.Entity;
			}
			set
			{
				KhachSan previousValue = this._KhachSan.Entity;
				if (((previousValue != value) 
							|| (this._KhachSan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachSan.Entity = null;
						previousValue.TienNghi = null;
					}
					this._KhachSan.Entity = value;
					if ((value != null))
					{
						value.TienNghi = this;
						this._MaKS = value.MaKS;
					}
					else
					{
						this._MaKS = default(short);
					}
					this.SendPropertyChanged("KhachSan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DiemDanhGia")]
	public partial class DiemDanhGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _MaKS;
		
		private short _MaKH;
		
		private short _Lan;
		
		private System.Nullable<short> _SachSe;
		
		private System.Nullable<short> _ThoaiMai;
		
		private System.Nullable<short> _TienNghi;
		
		private System.Nullable<short> _PhucVu;
		
		private System.Nullable<short> _DangTien;
		
		private System.Nullable<short> _Wifi;
		
		private System.Nullable<short> _DiaDiem;
		
		private EntityRef<KhacHang> _KhacHang;
		
		private EntityRef<KhacHang> _KhacHang1;
		
		private EntityRef<KhachSan> _KhachSan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKSChanging(short value);
    partial void OnMaKSChanged();
    partial void OnMaKHChanging(short value);
    partial void OnMaKHChanged();
    partial void OnLanChanging(short value);
    partial void OnLanChanged();
    partial void OnSachSeChanging(System.Nullable<short> value);
    partial void OnSachSeChanged();
    partial void OnThoaiMaiChanging(System.Nullable<short> value);
    partial void OnThoaiMaiChanged();
    partial void OnTienNghiChanging(System.Nullable<short> value);
    partial void OnTienNghiChanged();
    partial void OnPhucVuChanging(System.Nullable<short> value);
    partial void OnPhucVuChanged();
    partial void OnDangTienChanging(System.Nullable<short> value);
    partial void OnDangTienChanged();
    partial void OnWifiChanging(System.Nullable<short> value);
    partial void OnWifiChanged();
    partial void OnDiaDiemChanging(System.Nullable<short> value);
    partial void OnDiaDiemChanged();
    #endregion
		
		public DiemDanhGia()
		{
			this._KhacHang = default(EntityRef<KhacHang>);
			this._KhacHang1 = default(EntityRef<KhacHang>);
			this._KhachSan = default(EntityRef<KhachSan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKS", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short MaKS
		{
			get
			{
				return this._MaKS;
			}
			set
			{
				if ((this._MaKS != value))
				{
					if (this._KhachSan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKSChanging(value);
					this.SendPropertyChanging();
					this._MaKS = value;
					this.SendPropertyChanged("MaKS");
					this.OnMaKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if ((this._KhacHang.HasLoadedOrAssignedValue || this._KhacHang1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lan", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short Lan
		{
			get
			{
				return this._Lan;
			}
			set
			{
				if ((this._Lan != value))
				{
					this.OnLanChanging(value);
					this.SendPropertyChanging();
					this._Lan = value;
					this.SendPropertyChanged("Lan");
					this.OnLanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SachSe", DbType="SmallInt")]
		public System.Nullable<short> SachSe
		{
			get
			{
				return this._SachSe;
			}
			set
			{
				if ((this._SachSe != value))
				{
					this.OnSachSeChanging(value);
					this.SendPropertyChanging();
					this._SachSe = value;
					this.SendPropertyChanged("SachSe");
					this.OnSachSeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoaiMai", DbType="SmallInt")]
		public System.Nullable<short> ThoaiMai
		{
			get
			{
				return this._ThoaiMai;
			}
			set
			{
				if ((this._ThoaiMai != value))
				{
					this.OnThoaiMaiChanging(value);
					this.SendPropertyChanging();
					this._ThoaiMai = value;
					this.SendPropertyChanged("ThoaiMai");
					this.OnThoaiMaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienNghi", DbType="SmallInt")]
		public System.Nullable<short> TienNghi
		{
			get
			{
				return this._TienNghi;
			}
			set
			{
				if ((this._TienNghi != value))
				{
					this.OnTienNghiChanging(value);
					this.SendPropertyChanging();
					this._TienNghi = value;
					this.SendPropertyChanged("TienNghi");
					this.OnTienNghiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhucVu", DbType="SmallInt")]
		public System.Nullable<short> PhucVu
		{
			get
			{
				return this._PhucVu;
			}
			set
			{
				if ((this._PhucVu != value))
				{
					this.OnPhucVuChanging(value);
					this.SendPropertyChanging();
					this._PhucVu = value;
					this.SendPropertyChanged("PhucVu");
					this.OnPhucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DangTien", DbType="SmallInt")]
		public System.Nullable<short> DangTien
		{
			get
			{
				return this._DangTien;
			}
			set
			{
				if ((this._DangTien != value))
				{
					this.OnDangTienChanging(value);
					this.SendPropertyChanging();
					this._DangTien = value;
					this.SendPropertyChanged("DangTien");
					this.OnDangTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wifi", DbType="SmallInt")]
		public System.Nullable<short> Wifi
		{
			get
			{
				return this._Wifi;
			}
			set
			{
				if ((this._Wifi != value))
				{
					this.OnWifiChanging(value);
					this.SendPropertyChanging();
					this._Wifi = value;
					this.SendPropertyChanged("Wifi");
					this.OnWifiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem", DbType="SmallInt")]
		public System.Nullable<short> DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this.OnDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._DiaDiem = value;
					this.SendPropertyChanged("DiaDiem");
					this.OnDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhacHang_DiemDanhGia", Storage="_KhacHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhacHang KhacHang
		{
			get
			{
				return this._KhacHang.Entity;
			}
			set
			{
				KhacHang previousValue = this._KhacHang.Entity;
				if (((previousValue != value) 
							|| (this._KhacHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhacHang.Entity = null;
						previousValue.DiemDanhGias.Remove(this);
					}
					this._KhacHang.Entity = value;
					if ((value != null))
					{
						value.DiemDanhGias.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(short);
					}
					this.SendPropertyChanged("KhacHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhacHang_DiemDanhGia1", Storage="_KhacHang1", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhacHang KhacHang1
		{
			get
			{
				return this._KhacHang1.Entity;
			}
			set
			{
				KhacHang previousValue = this._KhacHang1.Entity;
				if (((previousValue != value) 
							|| (this._KhacHang1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhacHang1.Entity = null;
						previousValue.DiemDanhGias1.Remove(this);
					}
					this._KhacHang1.Entity = value;
					if ((value != null))
					{
						value.DiemDanhGias1.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(short);
					}
					this.SendPropertyChanged("KhacHang1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachSan_DiemDanhGia", Storage="_KhachSan", ThisKey="MaKS", OtherKey="MaKS", IsForeignKey=true)]
		public KhachSan KhachSan
		{
			get
			{
				return this._KhachSan.Entity;
			}
			set
			{
				KhachSan previousValue = this._KhachSan.Entity;
				if (((previousValue != value) 
							|| (this._KhachSan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachSan.Entity = null;
						previousValue.DiemDanhGias.Remove(this);
					}
					this._KhachSan.Entity = value;
					if ((value != null))
					{
						value.DiemDanhGias.Add(this);
						this._MaKS = value.MaKS;
					}
					else
					{
						this._MaKS = default(short);
					}
					this.SendPropertyChanged("KhachSan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonDatPhong")]
	public partial class DonDatPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_ddp;
		
		private System.Nullable<short> _MaKS;
		
		private System.Nullable<short> _MaKH;
		
		private System.Nullable<decimal> _thanh_tien;
		
		private System.Nullable<System.DateTime> _ngay_dat;
		
		private System.Nullable<bool> _DanhGia;
		
		private EntitySet<ChiTietDatPhong> _ChiTietDatPhongs;
		
		private EntityRef<KhacHang> _KhacHang;
		
		private EntityRef<KhachSan> _KhachSan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ddpChanging(int value);
    partial void Onid_ddpChanged();
    partial void OnMaKSChanging(System.Nullable<short> value);
    partial void OnMaKSChanged();
    partial void OnMaKHChanging(System.Nullable<short> value);
    partial void OnMaKHChanged();
    partial void Onthanh_tienChanging(System.Nullable<decimal> value);
    partial void Onthanh_tienChanged();
    partial void Onngay_datChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_datChanged();
    partial void OnDanhGiaChanging(System.Nullable<bool> value);
    partial void OnDanhGiaChanged();
    #endregion
		
		public DonDatPhong()
		{
			this._ChiTietDatPhongs = new EntitySet<ChiTietDatPhong>(new Action<ChiTietDatPhong>(this.attach_ChiTietDatPhongs), new Action<ChiTietDatPhong>(this.detach_ChiTietDatPhongs));
			this._KhacHang = default(EntityRef<KhacHang>);
			this._KhachSan = default(EntityRef<KhachSan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ddp", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_ddp
		{
			get
			{
				return this._id_ddp;
			}
			set
			{
				if ((this._id_ddp != value))
				{
					this.Onid_ddpChanging(value);
					this.SendPropertyChanging();
					this._id_ddp = value;
					this.SendPropertyChanged("id_ddp");
					this.Onid_ddpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKS", DbType="SmallInt")]
		public System.Nullable<short> MaKS
		{
			get
			{
				return this._MaKS;
			}
			set
			{
				if ((this._MaKS != value))
				{
					if (this._KhachSan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKSChanging(value);
					this.SendPropertyChanging();
					this._MaKS = value;
					this.SendPropertyChanged("MaKS");
					this.OnMaKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="SmallInt")]
		public System.Nullable<short> MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KhacHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanh_tien", DbType="Decimal(15,0)")]
		public System.Nullable<decimal> thanh_tien
		{
			get
			{
				return this._thanh_tien;
			}
			set
			{
				if ((this._thanh_tien != value))
				{
					this.Onthanh_tienChanging(value);
					this.SendPropertyChanging();
					this._thanh_tien = value;
					this.SendPropertyChanged("thanh_tien");
					this.Onthanh_tienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_dat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_dat
		{
			get
			{
				return this._ngay_dat;
			}
			set
			{
				if ((this._ngay_dat != value))
				{
					this.Onngay_datChanging(value);
					this.SendPropertyChanging();
					this._ngay_dat = value;
					this.SendPropertyChanged("ngay_dat");
					this.Onngay_datChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhGia", DbType="Bit")]
		public System.Nullable<bool> DanhGia
		{
			get
			{
				return this._DanhGia;
			}
			set
			{
				if ((this._DanhGia != value))
				{
					this.OnDanhGiaChanging(value);
					this.SendPropertyChanging();
					this._DanhGia = value;
					this.SendPropertyChanged("DanhGia");
					this.OnDanhGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonDatPhong_ChiTietDatPhong", Storage="_ChiTietDatPhongs", ThisKey="id_ddp", OtherKey="dondat_id")]
		public EntitySet<ChiTietDatPhong> ChiTietDatPhongs
		{
			get
			{
				return this._ChiTietDatPhongs;
			}
			set
			{
				this._ChiTietDatPhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhacHang_DonDatPhong", Storage="_KhacHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhacHang KhacHang
		{
			get
			{
				return this._KhacHang.Entity;
			}
			set
			{
				KhacHang previousValue = this._KhacHang.Entity;
				if (((previousValue != value) 
							|| (this._KhacHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhacHang.Entity = null;
						previousValue.DonDatPhongs.Remove(this);
					}
					this._KhacHang.Entity = value;
					if ((value != null))
					{
						value.DonDatPhongs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(Nullable<short>);
					}
					this.SendPropertyChanged("KhacHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachSan_DonDatPhong", Storage="_KhachSan", ThisKey="MaKS", OtherKey="MaKS", IsForeignKey=true)]
		public KhachSan KhachSan
		{
			get
			{
				return this._KhachSan.Entity;
			}
			set
			{
				KhachSan previousValue = this._KhachSan.Entity;
				if (((previousValue != value) 
							|| (this._KhachSan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachSan.Entity = null;
						previousValue.DonDatPhongs.Remove(this);
					}
					this._KhachSan.Entity = value;
					if ((value != null))
					{
						value.DonDatPhongs.Add(this);
						this._MaKS = value.MaKS;
					}
					else
					{
						this._MaKS = default(Nullable<short>);
					}
					this.SendPropertyChanged("KhachSan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDatPhongs(ChiTietDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.DonDatPhong = this;
		}
		
		private void detach_ChiTietDatPhongs(ChiTietDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.DonDatPhong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HinhAnh")]
	public partial class HinhAnh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _MaKS;
		
		private string _src;
		
		private string _Note;
		
		private EntityRef<KhachSan> _KhachSan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKSChanging(short value);
    partial void OnMaKSChanged();
    partial void OnsrcChanging(string value);
    partial void OnsrcChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    #endregion
		
		public HinhAnh()
		{
			this._KhachSan = default(EntityRef<KhachSan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKS", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short MaKS
		{
			get
			{
				return this._MaKS;
			}
			set
			{
				if ((this._MaKS != value))
				{
					if (this._KhachSan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKSChanging(value);
					this.SendPropertyChanging();
					this._MaKS = value;
					this.SendPropertyChanged("MaKS");
					this.OnMaKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_src", DbType="NVarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string src
		{
			get
			{
				return this._src;
			}
			set
			{
				if ((this._src != value))
				{
					this.OnsrcChanging(value);
					this.SendPropertyChanging();
					this._src = value;
					this.SendPropertyChanged("src");
					this.OnsrcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(50)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachSan_HinhAnh", Storage="_KhachSan", ThisKey="MaKS", OtherKey="MaKS", IsForeignKey=true)]
		public KhachSan KhachSan
		{
			get
			{
				return this._KhachSan.Entity;
			}
			set
			{
				KhachSan previousValue = this._KhachSan.Entity;
				if (((previousValue != value) 
							|| (this._KhachSan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachSan.Entity = null;
						previousValue.HinhAnhs.Remove(this);
					}
					this._KhachSan.Entity = value;
					if ((value != null))
					{
						value.HinhAnhs.Add(this);
						this._MaKS = value.MaKS;
					}
					else
					{
						this._MaKS = default(short);
					}
					this.SendPropertyChanged("KhachSan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhacHang")]
	public partial class KhacHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _MaKH;
		
		private string _UserName;
		
		private string _PassWord;
		
		private string _HoTen;
		
		private string _DiaChi;
		
		private string _Email;
		
		private string _SDT;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private EntitySet<DiemDanhGia> _DiemDanhGias;
		
		private EntitySet<DiemDanhGia> _DiemDanhGias1;
		
		private EntitySet<DonDatPhong> _DonDatPhongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(short value);
    partial void OnMaKHChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPassWordChanging(string value);
    partial void OnPassWordChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    #endregion
		
		public KhacHang()
		{
			this._DiemDanhGias = new EntitySet<DiemDanhGia>(new Action<DiemDanhGia>(this.attach_DiemDanhGias), new Action<DiemDanhGia>(this.detach_DiemDanhGias));
			this._DiemDanhGias1 = new EntitySet<DiemDanhGia>(new Action<DiemDanhGia>(this.attach_DiemDanhGias1), new Action<DiemDanhGia>(this.detach_DiemDanhGias1));
			this._DonDatPhongs = new EntitySet<DonDatPhong>(new Action<DonDatPhong>(this.attach_DonDatPhongs), new Action<DonDatPhong>(this.detach_DonDatPhongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassWord", DbType="NVarChar(50)")]
		public string PassWord
		{
			get
			{
				return this._PassWord;
			}
			set
			{
				if ((this._PassWord != value))
				{
					this.OnPassWordChanging(value);
					this.SendPropertyChanging();
					this._PassWord = value;
					this.SendPropertyChanged("PassWord");
					this.OnPassWordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhacHang_DiemDanhGia", Storage="_DiemDanhGias", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<DiemDanhGia> DiemDanhGias
		{
			get
			{
				return this._DiemDanhGias;
			}
			set
			{
				this._DiemDanhGias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhacHang_DiemDanhGia1", Storage="_DiemDanhGias1", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<DiemDanhGia> DiemDanhGias1
		{
			get
			{
				return this._DiemDanhGias1;
			}
			set
			{
				this._DiemDanhGias1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhacHang_DonDatPhong", Storage="_DonDatPhongs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<DonDatPhong> DonDatPhongs
		{
			get
			{
				return this._DonDatPhongs;
			}
			set
			{
				this._DonDatPhongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DiemDanhGias(DiemDanhGia entity)
		{
			this.SendPropertyChanging();
			entity.KhacHang = this;
		}
		
		private void detach_DiemDanhGias(DiemDanhGia entity)
		{
			this.SendPropertyChanging();
			entity.KhacHang = null;
		}
		
		private void attach_DiemDanhGias1(DiemDanhGia entity)
		{
			this.SendPropertyChanging();
			entity.KhacHang1 = this;
		}
		
		private void detach_DiemDanhGias1(DiemDanhGia entity)
		{
			this.SendPropertyChanging();
			entity.KhacHang1 = null;
		}
		
		private void attach_DonDatPhongs(DonDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.KhacHang = this;
		}
		
		private void detach_DonDatPhongs(DonDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.KhacHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachSan")]
	public partial class KhachSan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _MaKS;
		
		private string _TenKS;
		
		private System.Nullable<int> _MaKV;
		
		private string _GioiThieu;
		
		private string _hinh_1;
		
		private string _hinh_2;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private System.Nullable<short> _star;
		
		private System.Nullable<decimal> _point;
		
		private System.Nullable<bool> _QC;
		
		private System.Nullable<int> _LuotDanhGia;
		
		private EntitySet<ChiTietDatPhong> _ChiTietDatPhongs;
		
		private EntityRef<TienNghi> _TienNghi;
		
		private EntitySet<DiemDanhGia> _DiemDanhGias;
		
		private EntitySet<DonDatPhong> _DonDatPhongs;
		
		private EntitySet<HinhAnh> _HinhAnhs;
		
		private EntitySet<Phong> _Phongs;
		
		private EntityRef<KhuVuc> _KhuVuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKSChanging(short value);
    partial void OnMaKSChanged();
    partial void OnTenKSChanging(string value);
    partial void OnTenKSChanged();
    partial void OnMaKVChanging(System.Nullable<int> value);
    partial void OnMaKVChanged();
    partial void OnGioiThieuChanging(string value);
    partial void OnGioiThieuChanged();
    partial void Onhinh_1Changing(string value);
    partial void Onhinh_1Changed();
    partial void Onhinh_2Changing(string value);
    partial void Onhinh_2Changed();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnstarChanging(System.Nullable<short> value);
    partial void OnstarChanged();
    partial void OnpointChanging(System.Nullable<decimal> value);
    partial void OnpointChanged();
    partial void OnQCChanging(System.Nullable<bool> value);
    partial void OnQCChanged();
    partial void OnLuotDanhGiaChanging(System.Nullable<int> value);
    partial void OnLuotDanhGiaChanged();
    #endregion
		
		public KhachSan()
		{
			this._ChiTietDatPhongs = new EntitySet<ChiTietDatPhong>(new Action<ChiTietDatPhong>(this.attach_ChiTietDatPhongs), new Action<ChiTietDatPhong>(this.detach_ChiTietDatPhongs));
			this._TienNghi = default(EntityRef<TienNghi>);
			this._DiemDanhGias = new EntitySet<DiemDanhGia>(new Action<DiemDanhGia>(this.attach_DiemDanhGias), new Action<DiemDanhGia>(this.detach_DiemDanhGias));
			this._DonDatPhongs = new EntitySet<DonDatPhong>(new Action<DonDatPhong>(this.attach_DonDatPhongs), new Action<DonDatPhong>(this.detach_DonDatPhongs));
			this._HinhAnhs = new EntitySet<HinhAnh>(new Action<HinhAnh>(this.attach_HinhAnhs), new Action<HinhAnh>(this.detach_HinhAnhs));
			this._Phongs = new EntitySet<Phong>(new Action<Phong>(this.attach_Phongs), new Action<Phong>(this.detach_Phongs));
			this._KhuVuc = default(EntityRef<KhuVuc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKS", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short MaKS
		{
			get
			{
				return this._MaKS;
			}
			set
			{
				if ((this._MaKS != value))
				{
					this.OnMaKSChanging(value);
					this.SendPropertyChanging();
					this._MaKS = value;
					this.SendPropertyChanged("MaKS");
					this.OnMaKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKS", DbType="NVarChar(50)")]
		public string TenKS
		{
			get
			{
				return this._TenKS;
			}
			set
			{
				if ((this._TenKS != value))
				{
					this.OnTenKSChanging(value);
					this.SendPropertyChanging();
					this._TenKS = value;
					this.SendPropertyChanged("TenKS");
					this.OnTenKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKV", DbType="Int")]
		public System.Nullable<int> MaKV
		{
			get
			{
				return this._MaKV;
			}
			set
			{
				if ((this._MaKV != value))
				{
					if (this._KhuVuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKVChanging(value);
					this.SendPropertyChanging();
					this._MaKV = value;
					this.SendPropertyChanged("MaKV");
					this.OnMaKVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiThieu", DbType="NVarChar(500)")]
		public string GioiThieu
		{
			get
			{
				return this._GioiThieu;
			}
			set
			{
				if ((this._GioiThieu != value))
				{
					this.OnGioiThieuChanging(value);
					this.SendPropertyChanging();
					this._GioiThieu = value;
					this.SendPropertyChanged("GioiThieu");
					this.OnGioiThieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_1", DbType="NVarChar(50)")]
		public string hinh_1
		{
			get
			{
				return this._hinh_1;
			}
			set
			{
				if ((this._hinh_1 != value))
				{
					this.Onhinh_1Changing(value);
					this.SendPropertyChanging();
					this._hinh_1 = value;
					this.SendPropertyChanged("hinh_1");
					this.Onhinh_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_2", DbType="NVarChar(50)")]
		public string hinh_2
		{
			get
			{
				return this._hinh_2;
			}
			set
			{
				if ((this._hinh_2 != value))
				{
					this.Onhinh_2Changing(value);
					this.SendPropertyChanging();
					this._hinh_2 = value;
					this.SendPropertyChanged("hinh_2");
					this.Onhinh_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(150)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_star", DbType="SmallInt")]
		public System.Nullable<short> star
		{
			get
			{
				return this._star;
			}
			set
			{
				if ((this._star != value))
				{
					this.OnstarChanging(value);
					this.SendPropertyChanging();
					this._star = value;
					this.SendPropertyChanged("star");
					this.OnstarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_point", DbType="Decimal(2,1)")]
		public System.Nullable<decimal> point
		{
			get
			{
				return this._point;
			}
			set
			{
				if ((this._point != value))
				{
					this.OnpointChanging(value);
					this.SendPropertyChanging();
					this._point = value;
					this.SendPropertyChanged("point");
					this.OnpointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QC", DbType="Bit")]
		public System.Nullable<bool> QC
		{
			get
			{
				return this._QC;
			}
			set
			{
				if ((this._QC != value))
				{
					this.OnQCChanging(value);
					this.SendPropertyChanging();
					this._QC = value;
					this.SendPropertyChanged("QC");
					this.OnQCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuotDanhGia", DbType="Int")]
		public System.Nullable<int> LuotDanhGia
		{
			get
			{
				return this._LuotDanhGia;
			}
			set
			{
				if ((this._LuotDanhGia != value))
				{
					this.OnLuotDanhGiaChanging(value);
					this.SendPropertyChanging();
					this._LuotDanhGia = value;
					this.SendPropertyChanged("LuotDanhGia");
					this.OnLuotDanhGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachSan_ChiTietDatPhong", Storage="_ChiTietDatPhongs", ThisKey="MaKS", OtherKey="maks")]
		public EntitySet<ChiTietDatPhong> ChiTietDatPhongs
		{
			get
			{
				return this._ChiTietDatPhongs;
			}
			set
			{
				this._ChiTietDatPhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachSan_TienNghi", Storage="_TienNghi", ThisKey="MaKS", OtherKey="MaKS", IsUnique=true, IsForeignKey=false)]
		public TienNghi TienNghi
		{
			get
			{
				return this._TienNghi.Entity;
			}
			set
			{
				TienNghi previousValue = this._TienNghi.Entity;
				if (((previousValue != value) 
							|| (this._TienNghi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TienNghi.Entity = null;
						previousValue.KhachSan = null;
					}
					this._TienNghi.Entity = value;
					if ((value != null))
					{
						value.KhachSan = this;
					}
					this.SendPropertyChanged("TienNghi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachSan_DiemDanhGia", Storage="_DiemDanhGias", ThisKey="MaKS", OtherKey="MaKS")]
		public EntitySet<DiemDanhGia> DiemDanhGias
		{
			get
			{
				return this._DiemDanhGias;
			}
			set
			{
				this._DiemDanhGias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachSan_DonDatPhong", Storage="_DonDatPhongs", ThisKey="MaKS", OtherKey="MaKS")]
		public EntitySet<DonDatPhong> DonDatPhongs
		{
			get
			{
				return this._DonDatPhongs;
			}
			set
			{
				this._DonDatPhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachSan_HinhAnh", Storage="_HinhAnhs", ThisKey="MaKS", OtherKey="MaKS")]
		public EntitySet<HinhAnh> HinhAnhs
		{
			get
			{
				return this._HinhAnhs;
			}
			set
			{
				this._HinhAnhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachSan_Phong", Storage="_Phongs", ThisKey="MaKS", OtherKey="MaKS")]
		public EntitySet<Phong> Phongs
		{
			get
			{
				return this._Phongs;
			}
			set
			{
				this._Phongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhuVuc_KhachSan", Storage="_KhuVuc", ThisKey="MaKV", OtherKey="MaKV", IsForeignKey=true)]
		public KhuVuc KhuVuc
		{
			get
			{
				return this._KhuVuc.Entity;
			}
			set
			{
				KhuVuc previousValue = this._KhuVuc.Entity;
				if (((previousValue != value) 
							|| (this._KhuVuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhuVuc.Entity = null;
						previousValue.KhachSans.Remove(this);
					}
					this._KhuVuc.Entity = value;
					if ((value != null))
					{
						value.KhachSans.Add(this);
						this._MaKV = value.MaKV;
					}
					else
					{
						this._MaKV = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhuVuc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDatPhongs(ChiTietDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.KhachSan = this;
		}
		
		private void detach_ChiTietDatPhongs(ChiTietDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.KhachSan = null;
		}
		
		private void attach_DiemDanhGias(DiemDanhGia entity)
		{
			this.SendPropertyChanging();
			entity.KhachSan = this;
		}
		
		private void detach_DiemDanhGias(DiemDanhGia entity)
		{
			this.SendPropertyChanging();
			entity.KhachSan = null;
		}
		
		private void attach_DonDatPhongs(DonDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.KhachSan = this;
		}
		
		private void detach_DonDatPhongs(DonDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.KhachSan = null;
		}
		
		private void attach_HinhAnhs(HinhAnh entity)
		{
			this.SendPropertyChanging();
			entity.KhachSan = this;
		}
		
		private void detach_HinhAnhs(HinhAnh entity)
		{
			this.SendPropertyChanging();
			entity.KhachSan = null;
		}
		
		private void attach_Phongs(Phong entity)
		{
			this.SendPropertyChanging();
			entity.KhachSan = this;
		}
		
		private void detach_Phongs(Phong entity)
		{
			this.SendPropertyChanging();
			entity.KhachSan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhuVuc")]
	public partial class KhuVuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKV;
		
		private string _TenKV;
		
		private string _images;
		
		private EntitySet<KhachSan> _KhachSans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKVChanging(int value);
    partial void OnMaKVChanged();
    partial void OnTenKVChanging(string value);
    partial void OnTenKVChanged();
    partial void OnimagesChanging(string value);
    partial void OnimagesChanged();
    #endregion
		
		public KhuVuc()
		{
			this._KhachSans = new EntitySet<KhachSan>(new Action<KhachSan>(this.attach_KhachSans), new Action<KhachSan>(this.detach_KhachSans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKV
		{
			get
			{
				return this._MaKV;
			}
			set
			{
				if ((this._MaKV != value))
				{
					this.OnMaKVChanging(value);
					this.SendPropertyChanging();
					this._MaKV = value;
					this.SendPropertyChanged("MaKV");
					this.OnMaKVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKV", DbType="NVarChar(50)")]
		public string TenKV
		{
			get
			{
				return this._TenKV;
			}
			set
			{
				if ((this._TenKV != value))
				{
					this.OnTenKVChanging(value);
					this.SendPropertyChanging();
					this._TenKV = value;
					this.SendPropertyChanged("TenKV");
					this.OnTenKVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_images", DbType="NVarChar(30)")]
		public string images
		{
			get
			{
				return this._images;
			}
			set
			{
				if ((this._images != value))
				{
					this.OnimagesChanging(value);
					this.SendPropertyChanging();
					this._images = value;
					this.SendPropertyChanged("images");
					this.OnimagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhuVuc_KhachSan", Storage="_KhachSans", ThisKey="MaKV", OtherKey="MaKV")]
		public EntitySet<KhachSan> KhachSans
		{
			get
			{
				return this._KhachSans;
			}
			set
			{
				this._KhachSans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KhachSans(KhachSan entity)
		{
			this.SendPropertyChanging();
			entity.KhuVuc = this;
		}
		
		private void detach_KhachSans(KhachSan entity)
		{
			this.SendPropertyChanging();
			entity.KhuVuc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiPhong")]
	public partial class LoaiPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _MaLoai;
		
		private string _TenLoai;
		
		private EntitySet<ChiTietDatPhong> _ChiTietDatPhongs;
		
		private EntitySet<Phong> _Phongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiChanging(byte value);
    partial void OnMaLoaiChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    #endregion
		
		public LoaiPhong()
		{
			this._ChiTietDatPhongs = new EntitySet<ChiTietDatPhong>(new Action<ChiTietDatPhong>(this.attach_ChiTietDatPhongs), new Action<ChiTietDatPhong>(this.detach_ChiTietDatPhongs));
			this._Phongs = new EntitySet<Phong>(new Action<Phong>(this.attach_Phongs), new Action<Phong>(this.detach_Phongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", AutoSync=AutoSync.OnInsert, DbType="TinyInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public byte MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(50)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiPhong_ChiTietDatPhong", Storage="_ChiTietDatPhongs", ThisKey="MaLoai", OtherKey="maloai")]
		public EntitySet<ChiTietDatPhong> ChiTietDatPhongs
		{
			get
			{
				return this._ChiTietDatPhongs;
			}
			set
			{
				this._ChiTietDatPhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiPhong_Phong", Storage="_Phongs", ThisKey="MaLoai", OtherKey="MaLoai")]
		public EntitySet<Phong> Phongs
		{
			get
			{
				return this._Phongs;
			}
			set
			{
				this._Phongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDatPhongs(ChiTietDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.LoaiPhong = this;
		}
		
		private void detach_ChiTietDatPhongs(ChiTietDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.LoaiPhong = null;
		}
		
		private void attach_Phongs(Phong entity)
		{
			this.SendPropertyChanging();
			entity.LoaiPhong = this;
		}
		
		private void detach_Phongs(Phong entity)
		{
			this.SendPropertyChanging();
			entity.LoaiPhong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phong")]
	public partial class Phong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _MaKS;
		
		private byte _MaLoai;
		
		private System.Nullable<decimal> _Gia25;
		
		private System.Nullable<decimal> _Gia68;
		
		private System.Nullable<short> _SL;
		
		private EntityRef<KhachSan> _KhachSan;
		
		private EntityRef<LoaiPhong> _LoaiPhong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKSChanging(short value);
    partial void OnMaKSChanged();
    partial void OnMaLoaiChanging(byte value);
    partial void OnMaLoaiChanged();
    partial void OnGia25Changing(System.Nullable<decimal> value);
    partial void OnGia25Changed();
    partial void OnGia68Changing(System.Nullable<decimal> value);
    partial void OnGia68Changed();
    partial void OnSLChanging(System.Nullable<short> value);
    partial void OnSLChanged();
    #endregion
		
		public Phong()
		{
			this._KhachSan = default(EntityRef<KhachSan>);
			this._LoaiPhong = default(EntityRef<LoaiPhong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKS", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short MaKS
		{
			get
			{
				return this._MaKS;
			}
			set
			{
				if ((this._MaKS != value))
				{
					if (this._KhachSan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKSChanging(value);
					this.SendPropertyChanging();
					this._MaKS = value;
					this.SendPropertyChanged("MaKS");
					this.OnMaKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					if (this._LoaiPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia25", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Gia25
		{
			get
			{
				return this._Gia25;
			}
			set
			{
				if ((this._Gia25 != value))
				{
					this.OnGia25Changing(value);
					this.SendPropertyChanging();
					this._Gia25 = value;
					this.SendPropertyChanged("Gia25");
					this.OnGia25Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia68", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Gia68
		{
			get
			{
				return this._Gia68;
			}
			set
			{
				if ((this._Gia68 != value))
				{
					this.OnGia68Changing(value);
					this.SendPropertyChanging();
					this._Gia68 = value;
					this.SendPropertyChanged("Gia68");
					this.OnGia68Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL", DbType="SmallInt")]
		public System.Nullable<short> SL
		{
			get
			{
				return this._SL;
			}
			set
			{
				if ((this._SL != value))
				{
					this.OnSLChanging(value);
					this.SendPropertyChanging();
					this._SL = value;
					this.SendPropertyChanged("SL");
					this.OnSLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachSan_Phong", Storage="_KhachSan", ThisKey="MaKS", OtherKey="MaKS", IsForeignKey=true)]
		public KhachSan KhachSan
		{
			get
			{
				return this._KhachSan.Entity;
			}
			set
			{
				KhachSan previousValue = this._KhachSan.Entity;
				if (((previousValue != value) 
							|| (this._KhachSan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachSan.Entity = null;
						previousValue.Phongs.Remove(this);
					}
					this._KhachSan.Entity = value;
					if ((value != null))
					{
						value.Phongs.Add(this);
						this._MaKS = value.MaKS;
					}
					else
					{
						this._MaKS = default(short);
					}
					this.SendPropertyChanged("KhachSan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiPhong_Phong", Storage="_LoaiPhong", ThisKey="MaLoai", OtherKey="MaLoai", IsForeignKey=true)]
		public LoaiPhong LoaiPhong
		{
			get
			{
				return this._LoaiPhong.Entity;
			}
			set
			{
				LoaiPhong previousValue = this._LoaiPhong.Entity;
				if (((previousValue != value) 
							|| (this._LoaiPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiPhong.Entity = null;
						previousValue.Phongs.Remove(this);
					}
					this._LoaiPhong.Entity = value;
					if ((value != null))
					{
						value.Phongs.Add(this);
						this._MaLoai = value.MaLoai;
					}
					else
					{
						this._MaLoai = default(byte);
					}
					this.SendPropertyChanged("LoaiPhong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTK;
		
		private string _TenTK;
		
		private string _MatKhau;
		
		private string _VaiTro;
		
		private EntityRef<TaiKhoan> _TaiKhoan2;
		
		private EntityRef<TaiKhoan> _TaiKhoan1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTKChanging(int value);
    partial void OnMaTKChanged();
    partial void OnTenTKChanging(string value);
    partial void OnTenTKChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnVaiTroChanging(string value);
    partial void OnVaiTroChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._TaiKhoan2 = default(EntityRef<TaiKhoan>);
			this._TaiKhoan1 = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTK
		{
			get
			{
				return this._MaTK;
			}
			set
			{
				if ((this._MaTK != value))
				{
					if (this._TaiKhoan1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTKChanging(value);
					this.SendPropertyChanging();
					this._MaTK = value;
					this.SendPropertyChanged("MaTK");
					this.OnMaTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTK", DbType="NChar(10)")]
		public string TenTK
		{
			get
			{
				return this._TenTK;
			}
			set
			{
				if ((this._TenTK != value))
				{
					this.OnTenTKChanging(value);
					this.SendPropertyChanging();
					this._TenTK = value;
					this.SendPropertyChanged("TenTK");
					this.OnTenTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NChar(10)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VaiTro", DbType="NChar(10)")]
		public string VaiTro
		{
			get
			{
				return this._VaiTro;
			}
			set
			{
				if ((this._VaiTro != value))
				{
					this.OnVaiTroChanging(value);
					this.SendPropertyChanging();
					this._VaiTro = value;
					this.SendPropertyChanged("VaiTro");
					this.OnVaiTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_TaiKhoan", Storage="_TaiKhoan2", ThisKey="MaTK", OtherKey="MaTK", IsUnique=true, IsForeignKey=false)]
		public TaiKhoan TaiKhoan2
		{
			get
			{
				return this._TaiKhoan2.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan2.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan2.Entity = null;
						previousValue.TaiKhoan1 = null;
					}
					this._TaiKhoan2.Entity = value;
					if ((value != null))
					{
						value.TaiKhoan1 = this;
					}
					this.SendPropertyChanged("TaiKhoan2");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_TaiKhoan", Storage="_TaiKhoan1", ThisKey="MaTK", OtherKey="MaTK", IsForeignKey=true)]
		public TaiKhoan TaiKhoan1
		{
			get
			{
				return this._TaiKhoan1.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan1.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan1.Entity = null;
						previousValue.TaiKhoan2 = null;
					}
					this._TaiKhoan1.Entity = value;
					if ((value != null))
					{
						value.TaiKhoan2 = this;
						this._MaTK = value.MaTK;
					}
					else
					{
						this._MaTK = default(int);
					}
					this.SendPropertyChanged("TaiKhoan1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
